securityContext:
  runAsUser: 0

replicaCount: 3

image:
  registry: txo-galaxy-docker-local.artifactory.swg-devops.com
  repository: nifi/nifi-svt
  tag: v1.0
  username: salescda@cn.ibm.com
  password: KfgXtZNc33YEzBL2
  pullPolicy: IfNotPresent
  pullSecret:  artifactory-registry-secret

auth:
  ldap:
    enabled: true
    host: ldap://bluepages.ibm.com:389
    searchBase: ou=bluepages,o=ibm.com
    searchFilter: (mail={0})
    groupSearchBase: ou=memberlist,ou=ibmgroups,o=ibm.com
    groupObjectClass: groupOfUniqueNames
    groupSearchFilter: (cn=Optimizer_SVT*)
    groupMemberAttribute: uniquemember
    groupNameAttribute: cn
    admin: uid=AVPF6K672,c=cn,ou=bluepages,o=ibm.com


ingress:
  enabled: true
  annotations:
    ingress.bluemix.net/ALB-ID: private-crbl5p6krd0v5c9i4n2sdg-alb1;private-crbl5p6krd0v5c9i4n2sdg-alb2
    ingress.bluemix.net/redirect-to-https: "True"
    ingress.bluemix.net/client-max-body-size: 50m
  hosts:
    - nifi-svt.optimizer-svt.containers.ciocloudservices.ibm.com
  tls:
    - secretName: optimizer-tls
      hosts:
        - nifi-svt.optimizer-svt.containers.ciocloudservices.ibm.com



tlsSecrets:
  crt: |
    -----BEGIN CERTIFICATE-----
    MIIGUzCCBTugAwIBAgIDAR2GMA0GCSqGSIb3DQEBCwUAMGoxCzAJBgNVBAYTAlVT
    MTQwMgYDVQQKEytJbnRlcm5hdGlvbmFsIEJ1c2luZXNzIE1hY2hpbmVzIENvcnBv
    cmF0aW9uMSUwIwYDVQQDExxJQk0gSU5URVJOQUwgSU5URVJNRURJQVRFIENBMB4X
    DTE5MTEwNjA1MDAwMFoXDTIyMDIwODA0NTk1OVowgeIxCzAJBgNVBAYTAlVTMRYw
    FAYDVQQIEw1MaXR0bGV0b24sIE1BMRYwFAYDVQQHEw1MaXR0bGV0b24sIE1BMRAw
    DgYDVQQKEwdpYm0uY29tMQwwCgYDVQQLEwNJQ1MxQzBBBgNVBAMTOm5pZmktc3Z0
    Lm9wdGltaXplci1zdnQuY29udGFpbmVycy5jaW9jbG91ZHNlcnZpY2VzLmlibS5j
    b20xGTAXBgoJkiaJk/IsZAEBEwkwNDgxNkE2NzIxIzAhBgoJkiaJk/IsZAEDFhNt
    YWppbmdoZUBjbi5pYm0uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEApEV0gZEcxFNO9nsDfeQgepCALTL7hZbLzYRcQSt1udvnVZTflzxsrGCf3wqR
    +vnfjdvlcXPLopF+heC0F+fHAGn1icFGm43flaEjWj8m03uHYRr53/0nF9zkG1F8
    t1LITR0xRvZu/BBEbphBmeVJivnZ3P+4+dYK8+jNS1tY3oINb4GwAUIB+xBBATkC
    Xqop73FC+3fyzkxpMsDUKcN1XnLm8EgkRAU7fzctSW/iwB7vGqoynIb+LlUfQK6m
    5VfPwdMGjhb+dm+Th6dZl05FoW7Drm2ot0sq7aW3N9KdAP4IFJ8a/05ZpG3eQQ+f
    B6WySJaulMb1RXWaAINYKho0owIDAQABo4IChzCCAoMwRQYDVR0RBD4wPII6bmlm
    aS1zdnQub3B0aW1pemVyLXN2dC5jb250YWluZXJzLmNpb2Nsb3Vkc2VydmljZXMu
    aWJtLmNvbTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
    AQUFBwMCMIHUBgNVHR8EgcwwgckwgYSggYGgf6R9MHsxCzAJBgNVBAYTAlVTMTQw
    MgYDVQQKEytJbnRlcm5hdGlvbmFsIEJ1c2luZXNzIE1hY2hpbmVzIENvcnBvcmF0
    aW9uMSUwIwYDVQQDExxJQk0gSU5URVJOQUwgSU5URVJNRURJQVRFIENBMQ8wDQYD
    VQQDEwZDUkwxNDcwQKA+oDyGOmh0dHA6Ly9kYXltdnMxLnBvay5pYm0uY29tOjIw
    MDEvUEtJU2Vydi9jYWNlcnRzL0NSTDE0Ny5jcmwwHQYDVR0OBBYEFPHzclEa7yZB
    qnvWZcHmwdtTbJ81MB8GA1UdIwQYMBaAFAYv2seaHz+HUblN0PbarpdGSp3IMIHz
    BgNVHSAEgeswgegwgeUGBFUdIAAwgdwwdgYIKwYBBQUHAgEWamh0dHA6Ly93My0w
    My5pYm0uY29tL3RyYW5zZm9ybS9zYXMvYXMtd2ViLm5zZi9Db250ZW50RG9jc0J5
    VGl0bGUvSW5mb3JtYXRpb24rVGVjaG5vbG9neStTZWN1cml0eStTdGFuZGFyZHMw
    YgYIKwYBBQUHAgIwVgxUVXNlIG9mIHRoaXMgY2VydGlmaWNhdGUgc2hvdWxkIGFk
    aGVyZSB0byBJQk0gY29ycG9yYXRlIHN0YW5kYXJkcyBJVENTMTA0IGFuZCBJVENT
    MzAwMA0GCSqGSIb3DQEBCwUAA4IBAQAE+HTXzYQZZHHjPD8XI8E4lGSTama+8viE
    /wWJ50Os+gt7h1+lSEkEy6tXDs5uh1L5QNgQFq5iEy9TqH5T5YTjwwbcgXYcpQui
    Z1U6LQt8/kt9dPAtf4AUbeqBxYD4gR3lPH8mamj9rTh9VheUMd+Hr1ccSWT+tDWV
    55HoxlWbGGEpBQC6NT7KW+DhsFWvx0j/kl8pozSFCYEP7D5cLanzNi37R9eB6VoF
    o4VRr48B3tr95oSn0Rh8qQV2yKCjGKjKOr8afgdM3xDpFu7wsdOTNTlktjjGR12P
    7hU3lpI8Nf4ZdppErM1Ifbt+k2xc6leyQNz/0BIjAWr6P8cDz1kn
    -----END CERTIFICATE-----
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEApEV0gZEcxFNO9nsDfeQgepCALTL7hZbLzYRcQSt1udvnVZTf
    lzxsrGCf3wqR+vnfjdvlcXPLopF+heC0F+fHAGn1icFGm43flaEjWj8m03uHYRr5
    3/0nF9zkG1F8t1LITR0xRvZu/BBEbphBmeVJivnZ3P+4+dYK8+jNS1tY3oINb4Gw
    AUIB+xBBATkCXqop73FC+3fyzkxpMsDUKcN1XnLm8EgkRAU7fzctSW/iwB7vGqoy
    nIb+LlUfQK6m5VfPwdMGjhb+dm+Th6dZl05FoW7Drm2ot0sq7aW3N9KdAP4IFJ8a
    /05ZpG3eQQ+fB6WySJaulMb1RXWaAINYKho0owIDAQABAoIBAHHG6XsUVyhjyz1M
    1o5Lg3NgwmaL+Un9uAsQshUxVMj2VrQf+P13DI4YHqMNXy7GAuDufWynF1PyEgAI
    MrScBGl0+mv/Qjhbe5DXmvTW6L1xwcKwPIG3hWwxwoxpVEhlPfarUYYlCZnsanlv
    W4CMHvPzOcKoHCZu6gcmJ4saKeNydFexQCb8bBCJsme3M9Adwt44Syy5oVKbVVdA
    Lv42F1amHgvNSrvWfL2A2EGyT9jf5QFYpPIi+8lV6PN57ljNE7oN/sWo1mChToyW
    4jFQhzhs8x2OwjSAGN8Ljkszk66e/dFaZYw+JeQzjJsgHrJ7mN4KyINqpOxnDd5q
    SsIEqAECgYEA0ZtRN+06JiLfIsxSAUxVD2QhWzordXp/WjxmenhWxAzZS3TY7qIG
    N3f9nj23rUPSrDnzQJiwfcTlhJ39CMD8SMzZ9xS9w86I9RrbTEOo86sMYdMx6WG9
    oho3EUfnfR+9CaTesJ/CBT7KkF/l9TgbrOY4yJRpe0T0Rx/Hu1pXjEECgYEAyKFa
    1fe3Qrsac74Y7hSrcV/BXpFbNYVE7/8qOCJfIDzFEx/e+aocS0rTSekZeYz+OAre
    QLr4+8kTo/eW/N/k4t4LDtJeZRqMNPNmF5FDAT2luTxoPDPhvVkjIrIYnB9pWXud
    0O8u7Fdq5u10DYHJqeuvhnOUM/BgJi4cBfUfF+MCgYEAidi3RSyCPWpZjK0KkUf9
    +K1FMpXC1vPEpTdrvcc+aJh6nyEtOWLc68XByTuVfCFKf3FtBGJmT5AZ0WmFayhf
    whDWl6PQWOGPOIJ9Dl7A0d7/uaYHARECgYT0Ci1bk/I3hAwlV8r48jIlTWWD+gz4
    RnDxjxfrduIWNGA2HoR/ZwECgYEAvnXnLK7QC4phrzTsp795jdRwVp048BMHAarD
    YqzGj20BTYl4/JxP5e4vrL+bzndZsswmd17IFQarHYJilMbbm79c0gJFWEeeiHn0
    FjVxXZEvbSz6awR5rW4cW8ikcjmjoi4nAHy/l9/Y/Ua4YEYwsp2qcMHyFGiCblxh
    gApWLS8CgYBYGZVcwqOdpd/fNrmvaxeLLs1g4D6MKPWzZzCDaexixLUKHrxuBb2+
    u35RVrdR52OupGNsgLvyGxuZuA4Jv14dI7wEUxyw5okBMLUfzB28yvSnfv6LAjz2
    sVkafcTtyZJM6EuAKS3ZhL6DrI2v+rpH4N6UxfNnaTpg99OFRzhccw==
    -----END RSA PRIVATE KEY-----
